### ISSUE TITLE
Moving into feathers-ecosystem organization

### ISSUE THREAD

**Issue by dekelev** [dekelev/feathers-cassandra#4]
Hi @daffl, I've been using this project in production for over a year now and it proves to be very helpful.

I've synced most of the updates that you've added to feathers-objection, including the TypeScript definition file.

Can we move this repo into the feathers-ecosystem organization?

**Comment by daffl** [comment]
Totally. I sent you an invite to the organization which I think should let you move the repository. Are you planning to continue maintaining this module?

**Comment by dekelev** [comment]
Thanks! I'm still maintaining this module as normal.

**Comment by dekelev** [comment]
Can we expose the module here? https://docs.feathersjs.com/api/databases/adapters.html
Also, can you please change the repo settings to restrict direct commit into the master branch?

**Comment by daffl** [comment]
Done. And yes, you can add it to that page as well.
